"""versao_2_0_novos_campos

Revision ID: 3f9057bd8ad6
Revises: 5f07f4e1f2ea
Create Date: 2026-06-11 18:19:57.584754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9057bd8ad6'
down_revision = '5f07f4e1f2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('periodo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prioridade', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('prioridade')
        batch_op.drop_column('periodo')
        batch_op.drop_column('frequencia')

    # ### end Alembic commands ###
